const M = {
  tajinePoulet: "/assets/menu/dishes/menu-tajine-poulet.avif",
  tajineViandeFigues: "/assets/menu/dishes/menu-tajine-viande-figues.avif",
  tajineKefta: "/assets/menu/dishes/menu-tajine-kefta.avif",
  tajineCrevettes: "/assets/menu/dishes/menu-tajine-crevettes.avif",
  tanjia: "/assets/menu/dishes/menu-tanjia.avif",
  pastillaPoulet: "/assets/menu/dishes/menu-pastilla-poulet.avif",
  pastillaMer: "/assets/menu/dishes/menu-pastilla-mer.avif",
  seffa: "/assets/menu/dishes/menu-seffa.avif",
  kourain: "/assets/menu/dishes/menu-kourain.avif",
  rafissa: "/assets/menu/dishes/menu-rafissa.avif",
  viandeAlWalima: "/assets/menu/dishes/menu-viande-al-walima.avif",
  briouat: "/assets/menu/dishes/menu-briouat.avif",
  frites: "/assets/menu/dishes/menu-frites.avif",
  zaalouk: "/assets/menu/dishes/menu-zaalouk-tim1.avif",
  carottes: "/assets/menu/dishes/menu-carottes.avif",
  carottesConfites: "/assets/menu/dishes/menu-carottes-confites.avif",
  saladeMarocaine: "/assets/menu/dishes/menu-salade-marocaine.avif",
  saladeNicoise: "/assets/menu/dishes/menu-salade-nicoise.avif",
  saladeAvocatCrevettes: "/assets/menu/dishes/menu-salade-avocat-crevettes.avif",
  saladeAlWalima: "/assets/menu/dishes/menu-salade-al-walima.avif",
  poissonCreme: "/assets/menu/dishes/menu-poisson-creme.avif",
  theMarocain: "/assets/menu/dishes/menu-the-marocain.avif",
  cafeAlWalima: "/assets/menu/dishes/menu-cafe-al-walima.avif",
  tiramisu: "/assets/menu/dishes/menu-tiramisu.avif",
  cheesecake: "/assets/menu/dishes/menu-cheesecake.avif",
  cremeCaramel: "/assets/menu/dishes/menu-creme-caramel.avif",
  tarteCitron: "/assets/menu/dishes/menu-tarte-citron.avif",
} as const;

/**
 * Only dishes with a real photo in WEB MENU / WEB MENU 2 get an image.
 * No category pools, no stock placeholders, no sharing across unrelated plats.
 */
const MENU_ITEM_IMAGE_OVERRIDES: Record<string, string> = {
  "salade-marocaine": M.saladeMarocaine,
  "salade-nicoise": M.saladeNicoise,
  "salade-avocat-crevettes": M.saladeAvocatCrevettes,
  "salade-al-walima": M.saladeAlWalima,
  zaalouk: M.zaalouk,
  carottes: M.carottes,
  "carottes-confites": M.carottesConfites,
  "briouat-fromage": M.briouat,
  frites: M.frites,
  kourain: M.kourain,
  "seffa-nature": M.seffa,
  "seffa-royal": M.seffa,
  rafissa: M.rafissa,
  "viande-1-4": M.viandeAlWalima,
  "viande-1-2": M.viandeAlWalima,
  "viande-1kg": M.viandeAlWalima,
  "pastilla-poulet": M.pastillaPoulet,
  "pastilla-mer": M.pastillaMer,
  "tajine-poulet": M.tajinePoulet,
  "tajine-agneau-figues": M.tajineViandeFigues,
  "tajine-boeuf-figues": M.tajineViandeFigues,
  "tajine-kefta": M.tajineKefta,
  "tajine-crevettes": M.tajineCrevettes,
  "tanjia-1-4": M.tanjia,
  "tanjia-1-2": M.tanjia,
  "tanjia-1kg": M.tanjia,
  "saint-pierre": M.poissonCreme,
  tiramisu: M.tiramisu,
  cheesecake: M.cheesecake,
  "creme-caramel": M.cremeCaramel,
  "tarte-citron": M.tarteCitron,
  "the-marocain": M.theMarocain,
  "the-al-walima": M.theMarocain,
  "cafe-al-walima": M.cafeAlWalima,
};

export function resolveMenuItemImage(itemId: string): string | null {
  return MENU_ITEM_IMAGE_OVERRIDES[itemId] ?? null;
}
